// Export per-author review CSVs for author validation.
//   node scripts/export-review.mjs
//
// Groups incidents by the exact `authors` byline string and writes, under review/:
//   review/_recipients.csv          byline -> incident count + slugs (who gets what)
//   review/<safe-byline>/facts.csv  one row per incident: factual fields (editable) + locked keys
//   review/<safe-byline>/stages.csv one row per (incident x 7 stages): coded value (LOCKED) +
//                                   evidence quote/locator (author verifies) + author_comment
//   review/README.md                import + column guide
//
// Columns prefixed with the lock emoji are read-only for authors (your Section-5 coding /
// keys). Plain columns are what the author is asked to verify or correct. Re-import later
// with a companion script that maps facts.csv / stages.csv edits back into data/incidents/*.yml.
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import yaml from 'js-yaml';

const root = path.join(path.dirname(url.fileURLToPath(import.meta.url)), '..');
const dir = path.join(root, 'data', 'incidents');
const out = path.join(root, 'review');

const LOCK = '\u{1F512} '; // 🔒 prefix marks read-only columns
const STAGES = ['initial_access', 'privilege_escalation', 'reconnaissance', 'persistence', 'command_control', 'lateral_movement', 'action_on_objective'];

const csvCell = (v) => {
  const s = v == null ? '' : String(v);
  return /[",\n\r]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s;
};
const csv = (rows) => rows.map(r => r.map(csvCell).join(',')).join('\r\n') + '\r\n';
const safe = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 60) || 'unknown';

const incidents = fs.readdirSync(dir).filter(f => /\.ya?ml$/.test(f))
  .map(f => yaml.load(fs.readFileSync(path.join(dir, f), 'utf8')))
  .sort((a, b) => a.date.localeCompare(b.date) || a.slug.localeCompare(b.slug));

// group by exact byline
const groups = new Map();
for (const inc of incidents) {
  const key = (inc.authors || 'UNKNOWN').trim();
  if (!groups.has(key)) groups.set(key, []);
  groups.get(key).push(inc);
}

fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(out, { recursive: true });

// recipients index
const recRows = [['byline', 'n_incidents', 'has_questioned', 'folder', 'slugs']];
for (const [byline, incs] of [...groups].sort((a, b) => b[1].length - a[1].length)) {
  recRows.push([byline, incs.length, incs.some(i => i.questioned) ? 'yes' : '', safe(byline), incs.map(i => i.slug).join(' ')]);
}
fs.writeFileSync(path.join(out, '_recipients.csv'), csv(recRows));

const factsHeader = [
  LOCK + 'slug', LOCK + 'id', LOCK + 'title',
  'authors', 'date (YYYY-MM)', 'category', 'target',
  'source_url', 'source_venue', 'source_type', 'questioned (true/false)',
  'author_notes',
];
const stagesHeader = [
  LOCK + 'slug', LOCK + 'title', LOCK + 'stage',
  LOCK + 'coded_value', LOCK + 'justification (analyst)',
  'evidence_quote (verify/fix)', 'evidence_locator (verify/fix)',
  'author_comment',
];

let dirs = 0;
for (const [byline, incs] of groups) {
  const d = path.join(out, safe(byline));
  fs.mkdirSync(d, { recursive: true });
  dirs++;

  const factsRows = [factsHeader];
  const stageRows = [stagesHeader];
  for (const inc of incs) {
    factsRows.push([
      inc.slug, inc.id, inc.title,
      inc.authors, inc.date, inc.category, inc.target,
      inc.source?.url, inc.source?.venue, inc.source?.type, String(!!inc.questioned),
      '',
    ]);
    for (const st of STAGES) {
      const s = inc.stages?.[st];
      stageRows.push([
        inc.slug, inc.title, st,
        s ? s.value : '(none / not coded)',
        s ? s.justification : '',
        s ? s.evidence?.quote : '',
        s ? s.evidence?.locator : '',
        '',
      ]);
    }
  }
  fs.writeFileSync(path.join(d, 'facts.csv'), csv(factsRows));
  fs.writeFileSync(path.join(d, 'stages.csv'), csv(stageRows));
}

const readme = `# Author review packets

Generated by \`scripts/export-review.mjs\` from \`data/incidents/*.yml\`.

- \`_recipients.csv\` — one row per byline: how many incidents, which slugs, and the folder name. Use it to decide who to email. **Near-duplicate bylines are NOT merged** (e.g. "Zenity Labs" vs "Michael Bargury ... (Zenity Labs)") — merge recipients by hand if needed.
- \`<byline>/facts.csv\` and \`<byline>/stages.csv\` — import both as two tabs of one Google Sheet, then share that sheet with the author.

## Import into Google Sheets
1. New Google Sheet -> File -> Import -> Upload -> \`facts.csv\` -> "Insert new sheet(s)".
2. Repeat for \`stages.csv\`.
3. Select the lock-prefixed columns -> Data -> Protect range (or just tell the author not to touch them).
4. Share the sheet with that author (comment or edit access).

## Column rules
- **Lock-prefixed columns are read-only** — keys and the analyst's Section-5 kill-chain coding. Authors comment, they do not overwrite. You adjudicate coded values against \`CLAUDE.md\`.
- **Plain columns are for the author**: correct the factual fields (\`facts.csv\`), verify/fix the evidence \`quote\`/\`locator\` (\`stages.csv\`), and use \`author_notes\` / \`author_comment\` for anything else — including "you missed stage X" on a \`(none / not coded)\` row.
- \`stages.csv\` lists all 7 stages per incident so an author can dispute both what you coded and what you left null.
`;
fs.writeFileSync(path.join(out, 'README.md'), readme);

console.log(`wrote review/ : ${groups.size} bylines, ${dirs} folders, ${incidents.length} incidents`);
